import React from 'react'

function Iphone(props) {
  // useEffect(() => {}, [])

  // return <textarea id='simple-editor' style={{ display: 'none' }} />
  return (
    <div>
      <iframe title='iphone' style={{ width: '900px', height: '450px' }} src='http://tridiv.com/app/index.html?dmlldz1mdWxsJmRvYz17InNldHRpbmdzIjp7Im5hbWUiOiJpUGhvbmUgNFMiLCJsaWdodCI6InN0YXRpYyIsInNoYWRlIjoiLjMiLCJ0aW50IjoiLjMiLCJib3JkZXIiOiIwIiwiYmciOiIjM2E4OWI3Iiwiem9vbSI6IjEwMCIsIm1hdGNoIjoiMC41Iiwic25hcCI6Im9mZiJ9LCJzaGFwZXMiOlt7InR5cGUiOiJjdWJvaWQiLCJ5IjoiMS4xMjUiLCJ3IjoiMTYiLCJoIjoiLjUiLCJkIjoiMzIiLCJyeSI6IjE4MCIsImNyIjoiMi41IiwiY0FsbCI6IiMzMDMwMzAiLCJuYW1lIjpbImJhY2siXSwiaUJtIjoiaHR0cDovL3RyaWRpdi5jb20vZGVtb3MvaXBob25lNFMvYmFjay5wbmcifSx7InR5cGUiOiJjdWJvaWQiLCJ3IjoiMTYuNSIsImgiOiIxLjc1IiwiZCI6IjMyLjUiLCJjciI6IjIuNjI1IiwiY0FsbCI6IiNkNGQxY2YiLCJuYW1lIjpbIm1pZCJdfSx7InR5cGUiOiJjdWJvaWQiLCJ5IjoiLTEuMSIsInciOiIxNiIsImgiOiIuNDUiLCJkIjoiMzIiLCJjciI6IjIuNSIsImNBbGwiOiIjMzAzMDMwIiwiaVRwIjoiaHR0cDovL3RyaWRpdi5jb20vZGVtb3MvaXBob25lNFMvdG9wLnBuZyIsIm5hbWUiOlsidG9wIl19LHsidHlwZSI6ImN1Ym9pZCIsIngiOiItOC4zOCIsInoiOi0xMi41LCJ3IjoiLjUiLCJoIjoiLjI1IiwiZCI6IjEuNSIsInJ4IjoiMCIsInJ6IjotOTAsImNyIjoiLjI1IiwiY0FsbCI6IiNjYmM4YzYiLCJuYW1lIjpbImxvY2siXX0seyJ0eXBlIjoiY3lsaW5kZXIiLCJ4IjoiLTguMzgiLCJ6IjoiLTkuNSIsImRpYW1ldGVyIjoiMS4yNSIsImgiOiIwLjI1IiwicnoiOi05MCwic2lkZXMiOiIxMiIsImNBbGwiOiIjY2JjOGM2IiwibmFtZSI6WyJidG4tcGx1cyJdfSx7InR5cGUiOiJjeWxpbmRlciIsIngiOiItOC4zOCIsInoiOiItNyIsImRpYW1ldGVyIjoiMS4yNSIsImgiOiIwLjI1IiwicnoiOi05MCwic2lkZXMiOiIxMiIsImNBbGwiOiIjY2JjOGM2IiwibmFtZSI6WyJidG4tbGVzcyJdfSx7InR5cGUiOiJjdWJvaWQiLCJ4IjozLjUsInoiOiItMTYuMzgiLCJ3IjoiLjUiLCJoIjoiLjI1IiwiZCI6IjIuNzUiLCJyeCI6IjAiLCJyeSI6LTkwLCJyeiI6LTkwLCJjciI6Ii4yNSIsImNBbGwiOiIjY2JjOGM2IiwibmFtZSI6WyJwb3dlciJdfSx7InR5cGUiOiJjdWJvaWQiLCJ5IjoiLTEuMSIsInciOiIxNCIsImgiOiIuNCIsImQiOiIyMSIsImlUcCI6Imh0dHA6Ly90cmlkaXYuY29tL2RlbW9zL2lwaG9uZTRTL3NjcmVlbi5wbmciLCJuYW1lIjoiY3ViLTgifV19'></iframe>
    </div>
  )
}

export default Iphone
